/*
    Copyright 2020 Guillaume Bour.
    This file is part of «NextINpact app».

    «NextINpact app» is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    «NextINpact app» is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with «NextINpact app».  If not, see <http://www.gnu.org/licenses/>.
*/
.pragma library

var SMILEYS = {
    ":windu:": "windu.gif",
    ":baffe:": "baffe.gif",
    ":stress:": "stress.gif",
    ":jesquate:": "jesquate.gif",
    ":xzombi:": "cerf.gif",
    ":oui2:": "oui2.gif",
    ":duel1:": "lsvader.gif",
    ":D": "icon_mrgreen.gif",
    ":-D": "biggerGrin.gif",
    ":non:": "ripeer.gif",
    ":mdr:": "laugh.gif",
    ":incline:": "bowdown.gif",
    ":yes:": "yaisse.gif",
    ":chinois:": "chinese.gif",
    ":fumer:": "hat.gif",
    ":craint:": "frown.gif",
    ":pleure:": "pleure.gif",
    ":mad2:": "mad2.gif",
    ":oops:": "icon_redface.gif",
    ":keskidit:": "keskidit2.gif",
    ":byebye:": "byebye.gif",
    ":fou:": "fou.gif",
    ":prof:": "prof.gif",
    ":8": "lunettes1.gif",
    ":love:": "love.gif",
    ":roll:": "icon_rolleyes.gif",
    ":ooo:": "ooo.gif",
    ":francais:": "francais2.gif",
    ":eeek2:": "eeek2.gif",
    ":bravo:": "bravo.gif",
    ":reflechis:": "reflechis.gif",
    ":dors:": "dors2.gif",
    ":cartonjaune:": "cartonjaune.gif",
    ":cartonrouge:": "cartonrouge.gif",
    ":mad:": "mad.gif",
    ":smack:": "smack.gif",
    ":ouioui:": "ouioui.gif",
    ":censored:": "censored.gif",
    ":transpi:": "transpi.gif",
    ":langue:": "langue.gif",
    ":mdr2:": "mdr2.gif",
    ":bocul:": "bocul.gif",
    ":glasses:": "glasses.gif",
    ":google:": "google.gif",
    ":humour:": "humour.png",
    ":heben:": "heben.png",
    ":arrow:": "icon_arrow.gif",
    ":mrgreen:": "icon_mrgreen.gif",
    ":fume:": "fume.gif",
    ":frown:": "frown.gif",
    ":embarassed:": "embarassed.gif",
    ":eeek:": "eek.gif",
    ":duelsw:": "duelSW.gif",
    ":devil:": "devil.gif",
    ":copain:": "copain.png",
    ":bouletdujour:": "bouletdujour.gif",
    ":boulet:": "boulet.gif",
    ":birthday:": "birthday.gif",
    ":ouimaistusors:": "ouimaistusors.gif",
    ":musique:": "music.gif",
    ":merci:": "merci.gif",
    ":best:": "meilleur.gif",
    ":iloveyou:": "loveeyessmly.gif",
    ":kimouss:": "kimouss.gif",
    ":kill:": "kill.gif",
    ":neutral:": "icon_neutral.gif",
    ":zzz:": "zzzzz.gif",
    ":youhou:": "youhou.gif",
    ":yoda:": "yoda.gif",
    ":vomi2:": "vomi2.gif",
    ":vomi1:": "vomi1.gif",
    ":inpactitude:": "inpactitude3.gif",
    ":tchintchin:": "tchin.gif",
    ":sm:": "sm.gif",
    ":rhooo:": "rhooo.gif",
    ":bigssourire:": "biggerGrin.gif",
    ":nonnon:": "ripeer.gif",
    ":yaisse:": "yaisse.gif",
    ":crever:": "crever.gif",
    ":cap:": "maitrecapello.gif",
    ":naz:": "naz.gif",
    ":supervomi:": "supervomi.gif",
    ":pet:": "pet.gif",
    ":roule2:": "roule2.gif",
    ":dent:": "dent.gif",
    ":singe:": "singe.gif",
    ":mega:": "mega.gif",
    ":musicos:": "musicos.gif",
    ":roule:": "roule.gif",
    ":dd:": "dd.gif",
    ":phibee:": "phibee.gif",
    ":fete:": "fete.gif",
    ":cul:": "cul.gif",
    ":lapin:": "lapin.gif",
    ":ane:": "ane.gif",
    ":fou3:": "fou3.gif",
    ":poke:": "poke.gif",
    ":icq:": "icq.gif",
    ":surenchere:": "surenchere.gif",
    ":dix:": "dix.gif",
    ":neuf:": "neuf.gif",
    ":huit:": "huit.gif",
    ":sept:": "sept.gif",
    ":six:": "six.gif",
    ":cinq:": "cinq.gif",
    ":quatre:": "quatre.gif",
    ":trois:": "trois.gif",
    ":deux:": "deux.gif",
    ":un:": "un.gif",
    ":zero:": "zero.gif",
    ":top:": "top.gif",
    ":accident:": "accident.gif",
    ":tristan:": "bosse.gif",
    ":baton:": "baton.gif",
    ":prison:": "prison.gif",
    ":faim:": "faim.gif",
    ":photo:": "photo.gif",
    ":nimp:": "nimp.gif",
    ":ecrit:": "ecrit.gif",
    ":chant:": "chant.gif",
    ":brice:": "brice.gif",
    ":kc:": "kc.gif",
    ":mike:": "mike.gif",
    ":fr:": "france.gif",
    ":bisous:": "bisous.gif",
    ":win:": "win.gif",
    ":chaud:": "chaud.gif",
    ":pleure2:": "pleure2.gif",
    ":muscu:": "muscu.gif",
    ":cbon:": "mangezen.gif",
    ":pastaper:": "pastaper.gif",
    ":inpactitude2:": "inpactitude2.gif",
    ":troll:": "troll.gif",
    ":phiphi:": "phiphi.gif",
    ":perv:": "perv.gif",
    ":x:": "x.jpg",
    ":rtfm:": "rtfm.gif",
    ":marin:": "marin.gif",
    ":breton:": "breton.gif",
    ":google2:": "google2.gif",
    ":zarb:": "zarb.gif",
    ":sucre:": "sucre.gif",
    ":rem:": "rem.gif",
    ":plantage:": "plantage.gif",
    ":auto:": "auto.gif",
    ":pciwin:": "champion.gif"
}

function smiley(mark) {
    var s = SMILEYS[mark]
    if (s === undefined) {
        return undefined
    }

    return 'https://cdn2.nextinpact.com/smileys/' + s
}
